from commands2 import Command, Subsystem
from commands2.sysid import SysIdRoutine
import math
from phoenix6 import SignalLogger, swerve, units, utils, configs
from typing import Callable, overload
from wpilib import DriverStation, Notifier, RobotController
from wpilib.sysid import SysIdRoutineLog
from wpimath.geometry import Pose2d, Rotation2d
from ntcore import NetworkTableInstance

from generated.tuner_constants import TunerSwerveDrivetrain, TunerConstants

from pathplannerlib.auto import AutoBuilder
from pathplannerlib.config import RobotConfig, PIDConstants
from pathplannerlib.controller import PPHolonomicDriveController


class CommandSwerveDrivetrain(Subsystem, TunerSwerveDrivetrain):
    """
    Class that extends the Phoenix 6 SwerveDrivetrain class and implements
    Subsystem so it can easily be used in command-based projects.

    Generated by the 2026 Tuner X Swerve Project Generator
    https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
    """

    _SIM_LOOP_PERIOD: units.second = 0.004  # 4 ms

    _BLUE_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(0)
    """Blue alliance sees forward as 0 degrees (toward red alliance wall)"""
    _RED_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.fromDegrees(180)
    """Red alliance sees forward as 180 degrees (toward blue alliance wall)"""

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants: Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:  swerve.SwerveDrivetrainConstants
        :param modules:              Constants for each specific module
        :type modules:               list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants:        Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:         swerve.SwerveDrivetrainConstants
        :param odometry_update_frequency:   The frequency to run the odometry loop. If
                                            unspecified or set to 0 Hz, this is 250 Hz on
                                            CAN FD, and 100 Hz on CAN 2.0.
        :type odometry_update_frequency:    units.hertz
        :param modules:                     Constants for each specific module
        :type modules:                      list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        odometry_update_frequency: units.hertz,
        odometry_standard_deviation: tuple[float, float, float],
        vision_standard_deviation: tuple[float, float, float],
        modules: list[swerve.SwerveModuleConstants],
        /,
    ) -> None:
        """
        Constructs a CTRE SwerveDrivetrain using the specified constants.

        This constructs the underlying hardware devices, so users should not construct
        the devices themselves. If they need the devices, they can access them through
        getters in the classes.

        :param drivetrain_constants:        Drivetrain-wide constants for the swerve drive
        :type drivetrain_constants:         swerve.SwerveDrivetrainConstants
        :param odometry_update_frequency:   The frequency to run the odometry loop. If
                                            unspecified or set to 0 Hz, this is 250 Hz on
                                            CAN FD, and 100 Hz on CAN 2.0.
        :type odometry_update_frequency:    units.hertz
        :param odometry_standard_deviation: The standard deviation for odometry calculation
                                            in the form [x, y, theta]ᵀ, with units in meters
                                            and radians
        :type odometry_standard_deviation:  tuple[float, float, float]
        :param vision_standard_deviation:   The standard deviation for vision calculation
                                            in the form [x, y, theta]ᵀ, with units in meters
                                            and radians
        :type vision_standard_deviation:    tuple[float, float, float]
        :param modules:                     Constants for each specific module
        :type modules:                      list[swerve.SwerveModuleConstants]
        """
        ...

    @overload
    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0: None,
        arg1: None,
        arg2: None,
        arg3: None,
        /,
    ) -> None: ...

    def __init__(
        self,
        drivetrain_constants: swerve.SwerveDrivetrainConstants,
        arg0=None,
        arg1=None,
        arg2=None,
        arg3=None,
    ):
        Subsystem.__init__(self)
        TunerSwerveDrivetrain.__init__(
            self, drivetrain_constants, arg0, arg1, arg2, arg3
        )

        self._sim_notifier: Notifier | None = None
        self._last_sim_time: units.second = 0.0

        self._has_applied_operator_perspective = False
        """Keep track if we've ever applied the operator perspective before or not"""

        # Swerve requests to apply during SysId characterization
        self._translation_characterization = swerve.requests.SysIdSwerveTranslation()
        self._steer_characterization = swerve.requests.SysIdSwerveSteerGains()
        self._rotation_characterization = swerve.requests.SysIdSwerveRotation()

        self._sys_id_routine_translation = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Reduce dynamic voltage to 4 V to prevent brownout
                stepVoltage=4.0,
                # Log state with SignalLogger class
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdTranslation_State", SysIdRoutineLog.stateEnumToString(state)
                )
                and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._translation_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )
        """SysId routine for characterizing translation. This is used to find PID gains for the drive motors."""

        self._sys_id_routine_steer = SysIdRoutine(
            SysIdRoutine.Config(
                # Use default ramp rate (1 V/s) and timeout (10 s)
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Log state with SignalLogger class
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdSteer_State", SysIdRoutineLog.stateEnumToString(state)
                )
                and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: self.set_control(
                    self._steer_characterization.with_volts(output)
                ),
                lambda log: None,
                self,
            ),
        )
        """SysId routine for characterizing steer. This is used to find PID gains for the steer motors."""

        self._sys_id_routine_rotation = SysIdRoutine(
            SysIdRoutine.Config(
                # This is in radians per second², but SysId only supports "volts per second"
                rampRate=math.pi / 6,
                # Use dynamic voltage of 7 V
                stepVoltage=7.0,
                # Use default timeout (10 s)
                # Log state with SignalLogger class
                recordState=lambda state: SignalLogger.write_string(
                    "SysIdSteer_State", SysIdRoutineLog.stateEnumToString(state)
                )
                and None,
            ),
            SysIdRoutine.Mechanism(
                lambda output: (
                    # output is actually radians per second, but SysId only supports "volts"
                    self.set_control(
                        self._rotation_characterization.with_rotational_rate(output)
                    ),
                    # also log the requested output for SysId
                    SignalLogger.write_double("Rotational_Rate", output),
                )
                and None,
                lambda log: None,
                self,
            ),
        )
        """
        SysId routine for characterizing rotation.
        This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
        See the documentation of swerve.requests.SysIdSwerveRotation for info on importing the log to SysId.
        """

        self._sys_id_routine_to_apply = self._sys_id_routine_translation
        """The SysId routine to test"""

        self._ll_table = NetworkTableInstance.getDefault().getTable("limelight-bulldog")

        # Table for publishing module angles to Elastic
        self._module_table = NetworkTableInstance.getDefault().getTable("ModuleAngles")

        if utils.is_simulation():
            self._start_sim_thread()

        # --- PathPlanner AutoBuilder configuration ---
        # Load robot config from deploy/pathplanner/settings.json
        config = RobotConfig.fromGUISettings()

        AutoBuilder.configure(
            self._get_pose,                # Supplier<Pose2d> - robot pose
            self._reset_pose,              # Consumer<Pose2d> - reset odometry
            self._get_chassis_speeds,      # Supplier<ChassisSpeeds> - measured speeds
            self._drive_chassis_speeds,    # Consumer<ChassisSpeeds> - drive robot
            PPHolonomicDriveController(
                PIDConstants(15, 0.0, 0.0),   # Translation PID (tune to your robot)
                PIDConstants(15, 2, 1),   # Rotation PID (tune to your robot)
            ),
            config,                         # RobotConfig from GUI settings
            self._should_flip_path,         # BooleanSupplier - flip for red alliance
            self,                           # Subsystem requirement (this drivetrain)
        )

    def _get_ll_mt2_pose_estimate(self):
        """
        Read MegaTag2 botpose from the limelight-bulldog NetworkTables table.
        Returns (Pose2d, timestamp_seconds, tag_count) or None if no valid data.

        NT key: botpose_orb_wpiblue -> [x, y, z, roll, pitch, yaw, latency, tagCount, ...]
        """
        pose_array = self._ll_table.getEntry("botpose_orb_wpiblue").getDoubleArray([])

        # Limelight publishes at least 7 values: x, y, z, roll, pitch, yaw, latency
        # Index 7 = tag count (when available)
        if len(pose_array) < 7:
            return None     

        
        x = pose_array[0]
        y = pose_array[1]
        yaw_deg = pose_array[5]
        latency_ms = pose_array[6]
        tag_count = int(pose_array[7]) if len(pose_array) > 7 else 0

        # Timestamp: current FPGA time minus total latency
        timestamp = RobotController.getFPGATime() / 1e6 - latency_ms / 1000.0

        pose = Pose2d(x, y, Rotation2d.fromDegrees(yaw_deg))
        return pose, timestamp, tag_count

    def _get_robot_yaw_rate_deg_per_sec(self) -> float:
        """
        Return the robot's yaw rate in degrees per second from the Pigeon 2
        via the drivetrain's chassis speeds.
        """
        return math.degrees(self.get_state().speeds.omega)
 
    def update_vision_pose(self):
        """
        Read MegaTag2 pose from limelight-bulldog and feed it to the pose estimator.
        Call this every frame from RobotContainer.periodic().

        Rejects updates if:
          - No AprilTags seen (tagCount == 0)
          - Angular velocity > 360 deg/s (robot spinning too fast)
        """
        result = self._get_ll_mt2_pose_estimate()
        if result is None:
            return

        pose, timestamp, tag_count = result

        do_reject = False

        # Reject if no tags seen
        if tag_count == 0:
            do_reject = True

        # Reject if spinning faster than 360 deg/s
        if abs(self._get_robot_yaw_rate_deg_per_sec()) > 360:
            do_reject = True

        if not do_reject:
            # Standard deviations: trust x/y at 0.7m, ignore vision yaw (9999999)
            # because MT2 uses our Pigeon 2 yaw — we don't want vision to override it
            self.add_vision_measurement(
                pose,
                timestamp,
                (0.7, 0.7, 9999999),
            )
    
    def set_limelight_imu_mode(self, mode: int):
        """
        Set the Limelight IMU mode via NetworkTables.
        Mode 0 = external only (default)
        Mode 1 = seed internal IMU from external (use while disabled)
        Mode 4 = internal IMU + external IMU assist (use while enabled)
        """
        self._ll_table.getEntry("imumode_set").setDouble(mode)

    def apply_request(
        self, request: Callable[[], swerve.requests.SwerveRequest]
    ) -> Command:
        """
        Returns a command that applies the specified control request to this swerve drivetrain.

        :param request: Lambda returning the request to apply
        :type request: Callable[[], swerve.requests.SwerveRequest]
        :returns: Command to run
        :rtype: Command
        """
        return self.run(lambda: self.set_control(request()))

    def sys_id_quasistatic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Quasistatic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.

        :param direction: Direction of the SysId Quasistatic test
        :type direction: SysIdRoutine.Direction
        :returns: Command to run
        :rtype: Command
        """
        return self._sys_id_routine_to_apply.quasistatic(direction)

    def sys_id_dynamic(self, direction: SysIdRoutine.Direction) -> Command:
        """
        Runs the SysId Dynamic test in the given direction for the routine
        specified by self.sys_id_routine_to_apply.

        :param direction: Direction of the SysId Dynamic test
        :type direction: SysIdRoutine.Direction
        :returns: Command to run
        :rtype: Command
        """
        return self._sys_id_routine_to_apply.dynamic(direction)

    def periodic(self):
        # Periodically try to apply the operator perspective.
        # If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
        # This allows us to correct the perspective in case the robot code restarts mid-match.
        # Otherwise, only check and apply the operator perspective if the DS is disabled.
        # This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
        if not self._has_applied_operator_perspective or DriverStation.isDisabled():
            alliance_color = DriverStation.getAlliance()
            if alliance_color is not None:
                self.set_operator_perspective_forward(
                    self._RED_ALLIANCE_PERSPECTIVE_ROTATION
                    if alliance_color == DriverStation.Alliance.kRed
                    else self._BLUE_ALLIANCE_PERSPECTIVE_ROTATION
                )
                self._has_applied_operator_perspective = True

        state = self.get_state()
        if state is not None and state.module_states is not None:
            for i, mod_state in enumerate(state.module_states):
                self._module_table.getEntry(f"Module{i}_AngleDeg").setDouble(
                    mod_state.angle.degrees()
                )

    def _start_sim_thread(self):
        def _sim_periodic():
            current_time = utils.get_current_time_seconds()
            delta_time = current_time - self._last_sim_time
            self._last_sim_time = current_time

            # use the measured time delta, get battery voltage from WPILib
            self.update_sim_state(delta_time, RobotController.getBatteryVoltage())

        # Run simulation at a faster rate so PID gains behave more reasonably
        self._last_sim_time = utils.get_current_time_seconds()
        self._sim_notifier = Notifier(_sim_periodic)
        self._sim_notifier.startPeriodic(self._SIM_LOOP_PERIOD)

    def add_vision_measurement(
        self,
        vision_robot_pose: Pose2d,
        timestamp: units.second,
        vision_measurement_std_devs: tuple[float, float, float] | None = None,
    ):
        """
        Adds a vision measurement to the Kalman Filter. This will correct the
        odometry pose estimate while still accounting for measurement noise.

        Note that the vision measurement standard deviations passed into this method
        will continue to apply to future measurements until a subsequent call to
        set_vision_measurement_std_devs or this method.

        :param vision_robot_pose:           The pose of the robot as measured by the vision camera.
        :type vision_robot_pose:            Pose2d
        :param timestamp:                   The timestamp of the vision measurement in seconds.
        :type timestamp:                    second
        :param vision_measurement_std_devs: Standard deviations of the vision pose measurement
                                            in the form [x, y, theta]ᵀ, with units in meters
                                            and radians.
        :type vision_measurement_std_devs:  tuple[float, float, float] | None
        """
        TunerSwerveDrivetrain.add_vision_measurement(
            self,
            vision_robot_pose,
            utils.fpga_to_current_time(timestamp),
            vision_measurement_std_devs
        )

    def sample_pose_at(self, timestamp: units.second) -> Pose2d | None:
        """
        Return the pose at a given timestamp, if the buffer is not empty.

        :param timestamp: The timestamp of the pose in seconds.
        :type timestamp: second
        :returns: The pose at the given timestamp (or None if the buffer is empty).
        :rtype: Pose2d | None
        """
        return TunerSwerveDrivetrain.sample_pose_at(self, utils.fpga_to_current_time(timestamp))

    def _get_pose(self) -> Pose2d:
        """Return the current robot pose from the swerve pose estimator."""
        return self.get_state().pose

    def _reset_pose(self, pose: Pose2d) -> None:
        """Reset the pose estimator to the given pose."""
        self.reset_pose(pose)

    def _get_chassis_speeds(self):
        """Return the current measured ChassisSpeeds."""
        from wpimath.kinematics import ChassisSpeeds
        state = self.get_state()
        return state.speeds if state.speeds is not None else ChassisSpeeds()

    def _drive_chassis_speeds(self, speeds, feedforwards=None) -> None:
        """
        Drive the robot using the given ChassisSpeeds and optional DriveFeedforwards.
        PathPlanner calls this with (speeds, feedforwards) during path following.
        
        :param speeds: The desired robot-relative ChassisSpeeds
        :param feedforwards: PathPlanner DriveFeedforwards with per-module forces (optional)
        """
        request = swerve.requests.ApplyRobotSpeeds().with_speeds(speeds)

        if feedforwards is not None:
            try:
                fx = feedforwards.robotRelativeForcesX()
                fy = feedforwards.robotRelativeForcesY()
                request = (
                    request
                    .with_wheel_force_feedforwards_x(*fx)
                    .with_wheel_force_feedforwards_y(*fy)
                )
            except AttributeError:
                pass  # Feedforwards not available, drive without them

        self.set_control(request)

    def _should_flip_path(self) -> bool:
        """
        Return True if paths should be flipped for red alliance.
        PathPlanner paths are authored for blue alliance by default.
        """
        alliance = DriverStation.getAlliance()
        return alliance == DriverStation.Alliance.kRed
